language: node_js
node_js:
- node
services:
- postgresql
addons:
  postgresql: '9.6'
dist: trusty
sudo: false
notifications:
  email:
    on_success: change
    on_failure: always
install:
- npm i -g npm@5.7.1
- npm ci
before_script:
- psql -c 'create database "teesheet-test";' -U postgres
before_deploy:
- npm run build-client
- rm -rf node_modules
deploy:
  skip_cleanup: true
  provider: heroku
  app: teesheetapp
  api_key:
    secure: bFr1upyg0mwFt6xPr/p8rbgv5h2/7Gynj4zbD1OhfN2mXB31IztJJXU4YrZ5jgSm2lRJsUhY+2qPFANki/PH7NY3j70B4miUKpXw/G5NjivVP4n68RPbPwH/NMfC4HKb4WPx2bfsaXqTaQBz8QTm9Bof8wPs1oFtlvbN/sVtjLV76k949tS59AYRYSp3DRGhkq7fef9+0/ZCB6zkJSJsl/WTQDfrP5+mcKZwE5r48UGONddltoURRrrfYWKbK66iqIF0Te6LYe4Q8BZB6OLrlWCohbZVWXfGWU2LIYqdNHsf5CEwIZLOT0JdTfgvDLwNeLJUFG2cb0piXSMtX6Gtsav2gd41G6lXhdPA94Asm6C/QUUGw2rt+nUibWmAjm1EL/Adu/NezcDYiFxBun09scJjxcCfRdV43ezK2mBbaqFIBnwm+8FGevZeI5xtYM1YxdNrK0MAHJArItt5Ohl9MnO8+l9AY8RpnW5w60vdp3NoPyiKPhVgNzPN9HqnCB43V0bMde5dU2Kt82/wNU+7B/eU5z+XvOF6pzK4EN4LUiX56v8DVGiV//45NFHVaOzpwM/ffdYRte2H4IgSwac/8ATJpagoYmcMQqXLdlOffbO3JxNUqKe2weIj9of/3muks1KaE6UgB9Xfn9RhckTQfiHjwjWHeQlxmt+TNEB0N4k=
