language: node_js
node_js:
- node
services:
- postgresql
addons:
  postgresql: '9.6'
dist: trusty
sudo: false
notifications:
  email:
    on_success: change
    on_failure: always
install:
- npm i -g npm@5.7.1
- npm ci
before_script:
- psql -c 'create database "teesheet-test";' -U postgres
before_deploy:
- npm run build-client
- rm -rf node_modules
deploy:
  skip_cleanup: true
  provider: heroku
  app: teesheetapp
  api_key:
    secure: lzhd+zx6z+9fu3pKrkI7dGCmis1nBP6D0fhrz2x1CMftjqGwVHgMmkyNZxD+ObQhywCwso+ErMRnBD2S5hyNBz52GoD/qtc59Ubvui6nrvp/IYo6buQIcmX/z4YGVghfrseSSuBOjS2qEq9P2nsnZj863pW0BeuoYvkfJQG6B4u4cZbWSdP2FEazRywL7n8XmzYaNViiQ6smsGEhPWo/zl2uhu/R0i9SCsD7nC7JVKy6OoaOGSS6S6R2eRP/Dg6nLf5Lypr8tqnyfNHNRE9MdfO/cqMY0risFT4CBNQucv2d96vfSHK5smNG2kVqTk7cN1QLRSXK4Ucalt9N8QyHZabFHBUSWlbrZw035CN/1nytfBY9x043E+vSy+Oc8kuoJATEaiIQIYQ1WS2CZKmZwGmaCxcCUIBHop0w0UouznNJYy7OIY+v2QLq/qJHKlizQkBDpEksEHLrIrYcZaxJSD/gcmjIjyNyLWiTZ+LJ8ykN401AtPjZRnvoxwXyyZ633QexYCdbjyYx3WmM0WNUMGhIBk+bBZ6b/wyrGSYX8Vfq4NCkux+3cYHTU2ayRCu8Sc91ZVBNWvf6Gj12ErRtYbZPLizxI/f6SkkImxTHrhtZx7UQll/ZYi5lj9YFpxaN360/t2/T2JezYhVRpsGkzQcapf7vnGyCeD+bQ2X2Xl8=
