language: node_js
node_js:
- node
services:
- postgresql
addons:
  postgresql: '9.6'
dist: trusty
sudo: false
notifications:
  email:
    on_success: change
    on_failure: always
install:
- npm i -g npm@5.7.1
- npm ci
before_script:
- psql -c 'create database "teesheet-test";' -U postgres
before_deploy:
- npm run build-client
- rm -rf node_modules
deploy:
  skip_cleanup: true
  provider: heroku
  app: teesheetapp
  api_key:
    secure: qBRxsFXvvgGAZXJWA+zhNgoQju3ieRtzsrHObU4p4UJijqJ4brrL/YoCQ+sMvrXSnD3YHGGQhBJZZTcQxMLDrGgDLoA3Dgrpic/rE9PTiGYGZWoc3dv4StVkgzivOXrnoSVitlzOyd4/qbyiyKGpUCPPkSqV7lZgt8hT6viQXDu8oJa5X18o2it6HoeLMGqyCk7zPP5e8qbZPbLkzRUDa4e6QSD4A29UElsHCxdONZwuP8+cvpi7us8qe7pPYEorYATF2Pnmkmo/iPTHakJAkf5auZNt/Duade/Ro78kgiwF+/DDXMRQmkHyytGSsrmbXQ9E+i4bHQw0m1IYalpkYqlPtKUWZZxaT0MP3U5euj2sAKHFtX0tKbCc/X9s4kOt3hyv3Yu++gK2bKqXwzLANUGhnFTahGyrUTCy2ASeQi84Ov1OOt+KpCDi/ScKLLYk0XFqLAuLEnYl3AFElxqtinUaCWHH2/SVIk8Eywutwza6OjK+GE41k+kQUT/8R8Eqacm7F21qrgsKqq01799uZBvh1wIIneWtowD6P0yanrLyTwUZhQtlAPZN9ZvkQHxKe/Zykqa/h8jCG8RSl8iGWpfZkJF1/j6ZLhXy5CncBjo29BTcgMvFwaBjAcySLw5YaoX3cGi2RYFUyO9gbkvR+NJafTQFP/kLM2xYfflpqBM=
