const { YardageInfo, Hole, TeeGender } = require('../../server/db/models')

const holes = [
  {
    number: 1,
    yardage: 356,
    par: 4,
    mensHandicap: 13,
    yardageInfoId: 1,
  },
  {
    number: 2,
    yardage: 582,
    par: 5,
    mensHandicap: 3,
    yardageInfoId: 1,
  },
  {
    number: 3,
    yardage: 245,
    par: 3,
    mensHandicap: 15,
    yardageInfoId: 1,
  },
  {
    number: 4,
    yardage: 399,
    par: 4,
    mensHandicap: 7,
    yardageInfoId: 1,
  },
  {
    number: 5,
    yardage: 415,
    par: 4,
    mensHandicap: 5,
    yardageInfoId: 1,
  },
  {
    number: 6,
    yardage: 189,
    par: 3,
    mensHandicap: 17,
    yardageInfoId: 1,
  },
  {
    number: 7,
    yardage: 574,
    par: 5,
    mensHandicap: 1,
    yardageInfoId: 1,
  },
  {
    number: 8,
    yardage: 424,
    par: 4,
    mensHandicap: 9,
    yardageInfoId: 1,
  },
  {
    number: 9,
    yardage: 413,
    par: 4,
    mensHandicap: 11,
    yardageInfoId: 1,
  },
  {
    number: 10,
    yardage: 198,
    par: 3,
    mensHandicap: 16,
    yardageInfoId: 1,
  },
  {
    number: 11,
    yardage: 604,
    par: 5,
    mensHandicap: 2,
    yardageInfoId: 1,
  },
  {
    number: 12,
    yardage: 165,
    par: 3,
    mensHandicap: 18,
    yardageInfoId: 1,
  },
  {
    number: 13,
    yardage: 385,
    par: 4,
    mensHandicap: 10,
    yardageInfoId: 1,
  },
  {
    number: 14,
    yardage: 333,
    par: 4,
    mensHandicap: 12,
    yardageInfoId: 1,
  },
  {
    number: 15,
    yardage: 465,
    par: 4,
    mensHandicap: 6,
    yardageInfoId: 1,
  },
  {
    number: 16,
    yardage: 441,
    par: 4,
    mensHandicap: 8,
    yardageInfoId: 1,
  },
  {
    number: 17,
    yardage: 229,
    par: 3,
    mensHandicap: 14,
    yardageInfoId: 1,
  },
  {
    number: 18,
    yardage: 599,
    par: 5,
    mensHandicap: 4,
    yardageInfoId: 1,
  },
  {
    number: 1,
    yardage: 356,
    par: 4,
    mensHandicap: 13,
    yardageInfoId: 2,
  },
  {
    number: 2,
    yardage: 550,
    par: 5,
    mensHandicap: 3,
    yardageInfoId: 2,
  },
  {
    number: 3,
    yardage: 222,
    par: 3,
    mensHandicap: 15,
    yardageInfoId: 2,
  },
  {
    number: 4,
    yardage: 395,
    par: 4,
    mensHandicap: 7,
    yardageInfoId: 2,
  },
  {
    number: 5,
    yardage: 412,
    par: 4,
    mensHandicap: 5,
    yardageInfoId: 2,
  },
  {
    number: 6,
    yardage: 181,
    par: 3,
    mensHandicap: 17,
    yardageInfoId: 2,
  },
  {
    number: 7,
    yardage: 561,
    par: 5,
    mensHandicap: 1,
    yardageInfoId: 2,
  },
  {
    number: 8,
    yardage: 424,
    par: 4,
    mensHandicap: 9,
    yardageInfoId: 2,
  },
  {
    number: 9,
    yardage: 410,
    par: 4,
    mensHandicap: 11,
    yardageInfoId: 2,
  },
  {
    number: 10,
    yardage: 193,
    par: 3,
    mensHandicap: 16,
    yardageInfoId: 2,
  },
  {
    number: 11,
    yardage: 584,
    par: 5,
    mensHandicap: 2,
    yardageInfoId: 2,
  },
  {
    number: 12,
    yardage: 160,
    par: 3,
    mensHandicap: 18,
    yardageInfoId: 2,
  },
  {
    number: 13,
    yardage: 385,
    par: 4,
    mensHandicap: 10,
    yardageInfoId: 2,
  },
  {
    number: 14,
    yardage: 333,
    par: 4,
    mensHandicap: 12,
    yardageInfoId: 2,
  },
  {
    number: 15,
    yardage: 465,
    par: 4,
    mensHandicap: 6,
    yardageInfoId: 2,
  },
  {
    number: 16,
    yardage: 434,
    par: 4,
    mensHandicap: 8,
    yardageInfoId: 2,
  },
  {
    number: 17,
    yardage: 209,
    par: 3,
    mensHandicap: 14,
    yardageInfoId: 2,
  },
  {
    number: 18,
    yardage: 575,
    par: 5,
    mensHandicap: 4,
    yardageInfoId: 2,
  },
  {
    number: 1,
    yardage: 339,
    par: 4,
    womensHandicap: 13,
    yardageInfoId: 3,
  },
  {
    number: 2,
    yardage: 471,
    par: 5,
    womensHandicap: 3,
    yardageInfoId: 3,
  },
  {
    number: 3,
    yardage: 159,
    par: 3,
    womensHandicap: 15,
    yardageInfoId: 3,
  },
  {
    number: 4,
    yardage: 370,
    par: 4,
    womensHandicap: 7,
    yardageInfoId: 3,
  },
  {
    number: 5,
    yardage: 340,
    par: 4,
    womensHandicap: 5,
    yardageInfoId: 3,
  },
  {
    number: 6,
    yardage: 153,
    par: 3,
    womensHandicap: 17,
    yardageInfoId: 3,
  },
  {
    number: 7,
    yardage: 434,
    par: 5,
    womensHandicap: 1,
    yardageInfoId: 3,
  },
  {
    number: 8,
    yardage: 393,
    par: 4,
    womensHandicap: 9,
    yardageInfoId: 3,
  },
  {
    number: 9,
    yardage: 365,
    par: 4,
    womensHandicap: 11,
    yardageInfoId: 3,
  },
  {
    number: 10,
    yardage: 170,
    par: 3,
    womensHandicap: 16,
    yardageInfoId: 3,
  },
  {
    number: 11,
    yardage: 450,
    par: 5,
    womensHandicap: 2,
    yardageInfoId: 3,
  },
  {
    number: 12,
    yardage: 130,
    par: 3,
    womensHandicap: 18,
    yardageInfoId: 3,
  },
  {
    number: 13,
    yardage: 358,
    par: 4,
    womensHandicap: 10,
    yardageInfoId: 3,
  },
  {
    number: 14,
    yardage: 319,
    par: 4,
    womensHandicap: 12,
    yardageInfoId: 3,
  },
  {
    number: 15,
    yardage: 446,
    par: 4,
    womensHandicap: 6,
    yardageInfoId: 3,
  },
  {
    number: 16,
    yardage: 372,
    par: 4,
    womensHandicap: 8,
    yardageInfoId: 3,
  },
  {
    number: 17,
    yardage: 189,
    par: 3,
    womensHandicap: 14,
    yardageInfoId: 3,
  },
  {
    number: 18,
    yardage: 456,
    par: 5,
    womensHandicap: 4,
    yardageInfoId: 3,
  },
]

async function seedTees () {
  await TeeGender.create({
    formal: `Gentlemen's`,
    informal: `Men's`,
    abbreviation: `M`,
  })
  await TeeGender.create({
    formal: `Ladie's`,
    informal: `Women's`,
    abbreviation: `F`,
  })
  await YardageInfo.create({
    frontYardage: 3597,
    backYardage: 3419,
    totalYardage: 7016,
    frontPar: 36,
    backPar: 35,
    totalPar: 71,
    frontRating: 37.7,
    backRating: 36.7,
    frontSlope: 140,
    backSlope: 137,
    totalRating: 74.4,
    totalSlope: 139,
    courseId: 1,
    teeId: 5,
    teeGenderId: 1,
  })
  await YardageInfo.create({
    frontYardage: 3511,
    backYardage: 3338,
    totalYardage: 6849,
    frontPar: 36,
    backPar: 35,
    totalPar: 71,
    frontRating: 37.3,
    backRating: 36.3,
    frontSlope: 138,
    backSlope: 136,
    totalRating: 73.6,
    totalSlope: 137,
    courseId: 1,
    teeId: 2,
    teeGenderId: 1,
  })
  await YardageInfo.create({
    frontYardage: 3024,
    backYardage: 2890,
    totalYardage: 5914,
    frontPar: 36,
    backPar: 35,
    totalPar: 71,
    frontRating: 38.2,
    backRating: 37.1,
    frontSlope: 137,
    backSlope: 131,
    totalRating: 75.3,
    totalSlope: 134,
    courseId: 1,
    teeId: 3,
    teeGenderId: 2,
  })
  const holeProms = holes.map(hole => {
    return Hole.create(hole)
  })
  await Promise.all(holeProms)
  console.log(`Seeded ${holes.length} holes`)
}

module.exports = seedTees
